#!/usr/bin/env python3
"""Layerwise ParoQuant optimization for AlpamayoR1.

Adapted from paroquant/optimize.py for the AlpamayoR1 architecture, which
has two components that can be independently quantized:
    - VLM (Qwen3-VL language model layers): model.vlm.model.language_model.layers
    - Expert (trajectory prediction layers): model.expert.layers

Supports two calibration modes:
    1. Text-only (default): wikitext2, c4, redpajama tokenized data
    2. Multimodal (--calib-data): pre-computed inputs_embeds with image
       features fused, generated by generate_calib_data.py

Usage:
    # Optimize VLM layers with text-only data
    python paroquant/optimize_alpamayo.py \\
        --model /data/scratch/zekaili/Alpamayo-R1-10B \\
        --target vlm \\
        --datasets wikitext2 c4 \\
        --val-dataset wikitext2 \\
        --output-dir /data/scratch/zekaili/paroquant_results \\
        --params "channel_scales:0.05,angles:0.05" "weight:1e-5,quantizer:1e-6" \\
        --epochs 10 10 \\
        --group-size 128 --n-bit 4 --num-rotations 8 \\
        --train-size 128 --validation-size 32 \\
        --batch-size 4 --seqlen 2048 --seed 42

    # Optimize VLM layers with multimodal calibration data
    python paroquant/optimize_alpamayo.py \\
        --model /data/scratch/zekaili/Alpamayo-R1-10B \\
        --target vlm \\
        --calib-data /data/scratch/zekaili/calib_data_multimodal.pt \\
        --output-dir /data/scratch/zekaili/paroquant_results \\
        --params "channel_scales:0.05,angles:0.05" "weight:1e-5,quantizer:1e-6" \\
        --epochs 10 10 \\
        --group-size 128 --n-bit 4 --num-rotations 8 \\
        --train-size 128 --validation-size 32 \\
        --batch-size 4 --seed 42
"""

import torch
import torch.nn as nn
import simple_parsing
from dataclasses import dataclass, field
from tqdm import tqdm
from pathlib import Path
import json
from typing import Literal, Optional
import sys

# Upstream ParoQuant library (sibling repo at ../../paroquant/)
sys.path.append(str(Path(__file__).resolve().parents[2] / "paroquant"))
# src/ contains the alpamayo_r1 package
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "src"))

from paroquant.optimize import (
    optimize_module,
    get_random_rotation_pairs,
)
from paroquant.module import (
    PseudoQuantizedLinear,
    reset_angles_by_mask,
)
from paroquant.util import (
    set_module_by_name,
    load_tokenizer,
    get_calib_dataset,
    get_mixed_calib_dataset,
    get_named_linears,
    empty_cache,
    logger,
    CachedTensorShards,
)
from paroquant.convert_utils import transform_to_kernel_data


def get_alpamayo_blocks(model, target: str) -> nn.ModuleList:
    """Return the transformer layer list for the given AlpamayoR1 component."""
    if target == "expert":
        return model.expert.layers
    return model.vlm.model.language_model.layers


def move_alpamayo_embed(model, device, target: str):
    """Move embedding layers to device for first-layer input capture."""
    if target == "vlm":
        model.vlm.model.language_model.embed_tokens = (
            model.vlm.model.language_model.embed_tokens.to(device)
        )
        model.vlm.model.language_model.rotary_emb = (
            model.vlm.model.language_model.rotary_emb.to(device)
        )
    # Expert layers don't have a separate embedding — they receive hidden states


@torch.no_grad()
def catch_first_layer_input_alpamayo(
    model,
    blocks: nn.ModuleList,
    samples: torch.Tensor,
    batch_size: int,
    target: str,
) -> tuple[list[torch.Tensor], dict]:
    """Capture first layer input for AlpamayoR1 language model layers."""
    layer_kwargs = {}
    inps: list[torch.Tensor] = []

    class Catcher(nn.Module):
        def __init__(self, module):
            super().__init__()
            object.__setattr__(self, "module", module)

        def forward(self, inp, **kwargs):
            inps.append(inp)
            if len(layer_kwargs) == 0:
                layer_kwargs.update(kwargs)
            raise ValueError

        def __getattr__(self, name):
            return getattr(self.module, name)

    blocks[0] = Catcher(blocks[0])
    batch_size = samples.shape[0] if batch_size <= 0 else batch_size
    num_batches = samples.shape[0] // batch_size
    samples_batch = samples.chunk(num_batches)

    if target == "vlm":
        for s in samples_batch:
            try:
                model.vlm.model.language_model(
                    s.to(next(model.vlm.model.language_model.parameters()).device)
                )
            except ValueError:
                pass
    else:
        # For expert, feed through the language model to get hidden states
        for s in samples_batch:
            try:
                model.vlm.model.language_model(
                    s.to(next(model.vlm.model.language_model.parameters()).device)
                )
            except ValueError:
                pass

    blocks[0] = blocks[0].module

    layer_kwargs["use_cache"] = False
    if "past_key_value" in layer_kwargs:
        del layer_kwargs["past_key_value"]
    if "past_key_values" in layer_kwargs:
        del layer_kwargs["past_key_values"]

    return inps, layer_kwargs


@torch.no_grad()
def catch_first_layer_input_multimodal(
    model,
    blocks: nn.ModuleList,
    inputs_embeds: torch.Tensor,
    position_ids: torch.Tensor,
    attention_mask: torch.Tensor,
    batch_size: int,
) -> tuple[list[torch.Tensor], dict]:
    """Capture first layer input using pre-computed multimodal embeddings.

    Instead of passing token IDs through embed_tokens, we feed pre-computed
    inputs_embeds (with image features already fused) directly into the
    language model.
    """
    layer_kwargs = {}
    inps: list[torch.Tensor] = []

    class Catcher(nn.Module):
        def __init__(self, module):
            super().__init__()
            object.__setattr__(self, "module", module)

        def forward(self, inp, **kwargs):
            inps.append(inp)
            if len(layer_kwargs) == 0:
                layer_kwargs.update(kwargs)
            raise ValueError

        def __getattr__(self, name):
            return getattr(self.module, name)

    blocks[0] = Catcher(blocks[0])
    batch_size = inputs_embeds.shape[0] if batch_size <= 0 else batch_size
    num_batches = max(1, inputs_embeds.shape[0] // batch_size)

    embeds_batches = inputs_embeds.chunk(num_batches)
    pos_batches = position_ids.chunk(num_batches)
    mask_batches = attention_mask.chunk(num_batches)

    device = next(model.vlm.model.language_model.parameters()).device
    for e_batch, p_batch, m_batch in zip(embeds_batches, pos_batches, mask_batches):
        try:
            # Calib data stores position_ids as (batch, 3, seq_len) but the
            # language model expects (3, batch, seq_len) for M-RoPE.
            model.vlm.model.language_model(
                inputs_embeds=e_batch.to(device),
                position_ids=p_batch.permute(1, 0, 2).to(device),
                attention_mask=m_batch.to(device),
            )
        except ValueError:
            pass

    blocks[0] = blocks[0].module

    layer_kwargs["use_cache"] = False
    if "past_key_value" in layer_kwargs:
        del layer_kwargs["past_key_value"]
    if "past_key_values" in layer_kwargs:
        del layer_kwargs["past_key_values"]

    # All multimodal samples share identical sequence structure (same cameras,
    # same t0, same num_frames), so position embeddings are the same across
    # samples.  Reduce batch-dependent kwargs to batch=1 so they broadcast
    # to any batch size in forward_layer_batch.
    def _squeeze_batch(v):
        if isinstance(v, torch.Tensor) and v.dim() >= 1 and v.shape[0] == batch_size:
            return v[:1]
        if isinstance(v, tuple):
            return tuple(_squeeze_batch(x) for x in v)
        return v

    layer_kwargs = {k: _squeeze_batch(v) for k, v in layer_kwargs.items()}

    return inps, layer_kwargs


@dataclass(kw_only=True)
class Config:
    # Huggingface model path or local path to AlpamayoR1.
    model: str
    # Which component to quantize.
    target: Literal["vlm", "expert"] = "vlm"
    # The parameters to optimize at each stage and the corresponding learning rates.
    params: list[str]
    # The number of epochs for each stage of optimization.
    epochs: list[int]

    weight_decay: float = 0.01
    betas: tuple[float, float] = (0.9, 0.95)
    eps: float = 1e-10
    loss: Literal["mse", "smooth_l1"] = "smooth_l1"

    group_size: int
    n_bit: int
    num_rotations: int

    skipped_modules: list[str] = field(default_factory=list)

    # Text-only calibration (used when --calib-data is not set)
    datasets: list[str] = field(default_factory=lambda: ["wikitext2", "c4"])
    val_dataset: str = "wikitext2"
    seqlen: int = 2048

    # Multimodal calibration (overrides text-only when set)
    calib_data: Optional[str] = None

    train_size: int = 128
    validation_size: int = 32
    batch_size: int = 4
    val_batch_size: Optional[int] = None

    cache_shards: int = 1

    output_dir: str

    resume: bool = False
    checkpointing: bool = False

    seed: int


def main():
    args = simple_parsing.parse(
        Config, add_option_string_dash_variants=simple_parsing.DashVariant.DASH
    )
    print(args)

    # Store the results in a subdirectory.
    model_name = args.model.split("/")[-1]
    output_dir = Path(args.output_dir)
    output_dir = output_dir / model_name / args.target
    output_dir.mkdir(parents=True, exist_ok=True)

    device = "cuda"

    # Determine which params to optimize.
    params_to_optimize: list[dict[str, float]] = []
    for params in args.params:
        params = params.strip().split(",")
        param_dict = {}
        for param in params:
            param, lr = param.strip().split(":")
            param_dict[param.strip()] = float(lr.strip())
        params_to_optimize.append(param_dict)
    print(f"Parameters to optimize: {params_to_optimize}")

    # Save args
    with open(output_dir / "args.json", "w") as f:
        json.dump(vars(args), f, indent=2)

    # Load AlpamayoR1 model
    from alpamayo_r1.models.alpamayo_r1 import AlpamayoR1

    logger.info(f"Loading AlpamayoR1 from {args.model}...")
    model = AlpamayoR1.from_pretrained(args.model, dtype=torch.bfloat16)

    move_alpamayo_embed(model, device, args.target)
    blocks = get_alpamayo_blocks(model, args.target)
    val_batch_size = args.val_batch_size or args.batch_size

    if args.calib_data:
        # --- Multimodal calibration data ---
        logger.info(f"Loading multimodal calibration data from {args.calib_data}...")
        calib = torch.load(args.calib_data, map_location="cpu", weights_only=False)
        all_embeds = calib["inputs_embeds"]       # (N, seq_len, hidden_dim)
        all_pos_ids = calib["position_ids"]       # (N, 3, seq_len)
        all_attn_mask = calib["attention_mask"]    # (N, seq_len)
        n_total = all_embeds.shape[0]
        logger.info(
            f"Loaded {n_total} samples, seq_len={all_embeds.shape[1]}, "
            f"hidden_dim={all_embeds.shape[2]}"
        )
        del calib

        n_train = min(args.train_size, n_total - args.validation_size)
        n_val = min(args.validation_size, n_total - n_train)
        logger.info(f"Using {n_train} train + {n_val} validation samples")

        train_embeds = all_embeds[:n_train]
        train_pos = all_pos_ids[:n_train]
        train_mask = all_attn_mask[:n_train]
        val_embeds = all_embeds[n_train:n_train + n_val]
        val_pos = all_pos_ids[n_train:n_train + n_val]
        val_mask = all_attn_mask[n_train:n_train + n_val]
        del all_embeds, all_pos_ids, all_attn_mask

        logger.info("Capturing first layer input (multimodal)...")
        blocks[0].to(device)
        og_layer_input_batches, kwargs = catch_first_layer_input_multimodal(
            model, blocks, train_embeds, train_pos, train_mask,
            batch_size=args.batch_size,
        )
        og_layer_val_input_batches, _ = catch_first_layer_input_multimodal(
            model, blocks, val_embeds, val_pos, val_mask,
            batch_size=val_batch_size,
        )
        blocks[0].cpu()
        del train_embeds, train_pos, train_mask, val_embeds, val_pos, val_mask
        empty_cache()
    else:
        # --- Text-only calibration data ---
        tokenizer = model.tokenizer
        samples = get_mixed_calib_dataset(
            args.datasets,
            tokenizer=tokenizer,
            n_samples=args.train_size,
            block_size=args.seqlen,
            seed=args.seed,
            split="train",
        )
        samples = torch.stack(samples, dim=0).to(device)

        val_samples = get_calib_dataset(
            args.val_dataset,
            tokenizer=tokenizer,
            n_samples=args.validation_size,
            block_size=args.seqlen,
            seed=args.seed,
            split="validation",
        )
        val_samples = torch.stack(val_samples, dim=0).to(device)

        logger.info("Capturing first layer input...")
        blocks[0].to(device)
        og_layer_input_batches, kwargs = catch_first_layer_input_alpamayo(
            model, blocks, samples, batch_size=args.batch_size, target=args.target,
        )
        og_layer_val_input_batches, _ = catch_first_layer_input_alpamayo(
            model, blocks, val_samples, batch_size=val_batch_size, target=args.target,
        )
        blocks[0].cpu()
        del samples
        empty_cache()

    @torch.no_grad()
    def forward_layer_batch(
        layer: nn.Module,
        input_batched: list[torch.Tensor],
        kwargs: dict,
        store_device: torch.device,
        dtype: torch.dtype = torch.bfloat16,
        cast_to_dtype: torch.dtype = torch.bfloat16,
    ) -> list[torch.Tensor]:
        output_batched = []
        layer.to(device)
        # Cast kwargs tensors to match input dtype to avoid mixed-precision errors
        def _cast(v):
            if isinstance(v, torch.Tensor) and v.is_floating_point():
                return v.to(dtype)
            elif isinstance(v, tuple):
                return tuple(_cast(x) for x in v)
            return v
        casted_kwargs = {k: _cast(v) for k, v in kwargs.items()}
        for input_batch in input_batched:
            output = layer(input_batch.to(dtype).to(device), **casted_kwargs)
            if isinstance(output, tuple):
                output = output[0]
            if output.dtype != cast_to_dtype:
                output = output.to(cast_to_dtype)
            if output.device != store_device:
                output = output.to(store_device)
            output_batched.append(output)
        layer.cpu()
        empty_cache()
        return output_batched

    def set_checkpointing_enabled(module: nn.Module, enable: bool) -> None:
        for linear in get_named_linears(
            module, subclass=PseudoQuantizedLinear
        ).values():
            linear.enable_checkpoint = enable

    # Layerwise, multi-stage optimization.
    for layer_idx, layer in enumerate(tqdm(blocks)):
        empty_cache()
        logger.info(f"Capturing original layer output...")
        og_layer_output_batches = forward_layer_batch(
            layer, og_layer_input_batches, kwargs, store_device="cpu"
        )
        og_layer_val_output_batches = forward_layer_batch(
            layer, og_layer_val_input_batches, kwargs, store_device="cpu"
        )

        if layer_idx > 0:
            layer_input_batches = new_layer_output_batches
            layer_val_input_batches = new_layer_val_output_batches
        else:
            layer_input_batches = og_layer_input_batches
            layer_val_input_batches = og_layer_val_input_batches

        train_input_batches = layer_input_batches
        train_output_batches = og_layer_output_batches

        train_input_batches = CachedTensorShards(
            train_input_batches, args.cache_shards, target_device=device
        )
        train_output_batches = CachedTensorShards(
            train_output_batches, args.cache_shards, target_device=device
        )

        val_input_batches = [b.to(device) for b in layer_val_input_batches]
        val_output_batches = [b.to(device) for b in og_layer_val_output_batches]

        # Freeze all parameters
        for param in layer.parameters():
            param.requires_grad = False

        linear_modules = get_named_linears(layer)
        if args.resume:
            all_files_exist = True
            for name in linear_modules.keys():
                file_name = f"{layer_idx}.{name}.pt"
                file_path = output_dir / file_name
                if not file_path.exists() and name not in args.skipped_modules:
                    all_files_exist = False
                    break
        else:
            all_files_exist = False

        if not all_files_exist:
            logger.info(f"Initializing rotation parameters...")

        for name, old_module in linear_modules.items():
            if name in args.skipped_modules:
                continue

            if all_files_exist:
                existing_result_file = output_dir / f"{layer_idx}.{name}.pt"
                sd = torch.load(existing_result_file, map_location=device)
                new_module = PseudoQuantizedLinear.from_state_dict(sd)
                set_module_by_name(layer, name, new_module)
                continue

            old_module.to(device).half()

            num_pairs_factor = 0.5
            weight = old_module.weight.float()
            weight_grouped = weight.view(weight.shape[0], -1, args.group_size).permute(
                1, 0, 2
            )

            all_pairs = get_random_rotation_pairs(
                weight_grouped,
                group_size=args.group_size,
                num_rotations=args.num_rotations,
                num_pairs_factor=num_pairs_factor,
                seed=args.seed + layer_idx,
            )

            all_pairs = [
                torch.tensor(pairs, device="cpu", dtype=torch.int32)
                for pairs in all_pairs
            ]
            initial_angles = [
                torch.zeros(pairs.shape[0], device="cpu") for pairs in all_pairs
            ]
            initial_scales = torch.ones(
                1, weight.shape[1], dtype=torch.float16, device=device
            )

            npairs, angles, mask = transform_to_kernel_data(
                all_pairs,
                initial_angles,
                group_size=args.group_size,
            )
            npairs = npairs.to(device)
            angles = angles.to(device)
            mask = mask.to(device)
            rotation_pairs = [npairs, angles, mask]
            channel_scales = initial_scales

            new_module = PseudoQuantizedLinear(
                old_module,
                rotation_pairs,
                channel_scales,
                group_size=args.group_size,
                n_bits=args.n_bit,
                num_rotations=args.num_rotations,
            )

            set_module_by_name(layer, name, new_module)
            old_module.cpu()

        if not all_files_exist:
            layer.to(device).float()

            set_checkpointing_enabled(layer, args.checkpointing)
            for step, step_params_dict in enumerate(params_to_optimize):
                empty_cache()
                optim_params = []
                new_modules = get_named_linears(layer, subclass=PseudoQuantizedLinear)
                for new_module in new_modules.values():
                    new_module.set_optim_enabled(
                        **{param_name: True for param_name in step_params_dict.keys()},
                    )
                    for param_name, lr in step_params_dict.items():
                        optim_params.append(
                            dict(
                                params=new_module.get_optim_params(param_name),
                                lr=lr,
                                weight_decay=args.weight_decay,
                                betas=args.betas,
                                eps=args.eps,
                            )
                        )

                logger.info(
                    f"Optimizing layer {layer_idx}, step {step + 1}/{len(params_to_optimize)}: "
                    f"{', '.join([k for k in step_params_dict])}"
                )

                optimize_module(
                    layer,
                    (train_input_batches, train_output_batches),
                    (val_input_batches, val_output_batches),
                    kwargs,
                    optim_params,
                    loss_fn=args.loss,
                    n_iter=args.epochs[step],
                    early_stop=None,
                    post_optim_callback=reset_angles_by_mask,
                )

            set_checkpointing_enabled(layer, False)

            del (
                train_input_batches,
                train_output_batches,
                val_input_batches,
                val_output_batches,
            )
            empty_cache()

        else:
            logger.info(
                f"Skipping optimization for layer {layer_idx}: already been optimized."
            )

        layer.half().to(device)

        logger.info("Capturing new layer output...")
        new_layer_output_batches = forward_layer_batch(
            layer,
            layer_input_batches,
            kwargs,
            store_device="cpu",
            dtype=torch.float16,
            cast_to_dtype=torch.bfloat16,
        )
        new_layer_val_output_batches = forward_layer_batch(
            layer,
            layer_val_input_batches,
            kwargs,
            store_device="cpu",
            dtype=torch.float16,
            cast_to_dtype=torch.bfloat16,
        )

        og_layer_input_batches = og_layer_output_batches
        og_layer_val_input_batches = og_layer_val_output_batches

        if all_files_exist:
            layer.cpu()
            continue

        # Save the optimized result
        for name, module in get_named_linears(
            layer, subclass=PseudoQuantizedLinear
        ).items():
            result_file = output_dir / f"{layer_idx}.{name}.pt"
            torch.save(
                module.state_dict(),
                result_file,
            )

        layer.cpu()


if __name__ == "__main__":
    main()
